const players=[
 {id:13,name:"13",team:"Free agent",role:"top",strength:78,pool:72},
 {id:34,name:"34",team:"Free agent",role:"jungle",strength:39,pool:72},
 {id:369,name:"369",team:"Blue Otter",role:"support",strength:71,pool:68},
 {id:301,name:"3XA",team:"LOUD",role:"bot",strength:74,pool:64},
 {id:501,name:"5Fire",team:"Free agent",role:"support",strength:66,pool:61},
 {id:502,name:"5Kid",team:"7REX",role:"jungle",strength:70,pool:58},
 {id:601,name:"AAAAY",team:"Free agent",role:"mid",strength:63,pool:55},
 {id:602,name:"Abate",team:"Free agent",role:"top",strength:60,pool:50}
];
const champions=[
 ["swordman","Swordman",96,.20,true],["pyromancer","Pyromancer",88,.18,false],["dark_mage","Dark Mage",84,.16,false],["fighter","Fighter",79,.14,false],["planemage","Planemage",75,.12,false],["taoist","Taoist",72,.10,false],["android","Android",68,.08,false],["bomber","Bomber",64,.07,false],["circus_blade","Circus Blade",61,.06,false],["exorcist","Exorcist",57,.05,false],["lightning_mage","Lightning Mage",53,.04,false],["oni","Oni",48,.03,false]
].map(([id,name,mastery,buff,recent])=>({id,name,mastery,buff,recent,portrait:`../../../assets/champions/${id}.png`}));
const portraitCatalog=(await fetch("../../../data/catalog/portraits.json").then(response=>response.json())).portraits;
const coreNames=["Last hit","Skill avoid","Skill hit","Positioning","Control speed","Concentration","Mental","Judgement"];
const baseByPlayer={13:[91,78,80,50,92,64,68,48],34:[54,26,27,2,3,1,70,66],369:[72,74,68,70,76,69,73,71]};
const state={mode:"reading",selected:13,hovered:null,role:"all",team:"all",contract:"all",query:"",poolQuery:"",floor:0,champion:"swordman",pins:[],pinnedChampion:null,lock:false,radial:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const roleColor=r=>`var(--${r})`;const selectedPlayer=()=>players.find(p=>p.id===state.selected)||players[0];const selectedChampion=()=>champions.find(c=>c.id===state.champion)||champions[0];
function portraitStyle(id){const p=portraitCatalog[id];if(!p)return "";const scale=Math.max(46/p.frame.width,50/p.frame.height),x=-p.frame.x*scale+(46-p.frame.width*scale)/2,y=-p.frame.y*scale+(50-p.frame.height*scale)/2;return `width:${p.sheetWidth*scale}px;height:${p.sheetHeight*scale}px;transform:translate(${x}px,${y}px)`}
function setMode(mode,force=false){if(state.lock&&!force)return;state.mode=mode;$("#prototype").dataset.mode=mode;$("#modeName").textContent=mode[0].toUpperCase()+mode.slice(1);render();}
function renderRoster(){const visible=players.filter(p=>(state.role==="all"||p.role===state.role)&&(state.team==="all"||p.team===state.team)&&(state.contract==="all"||(state.contract==="free"?p.team==="Free agent":p.team!=="Free agent"))&&`${p.name} ${p.team} ${p.role}`.toLowerCase().includes(state.query.toLowerCase()));$("#rosterCount").textContent=`${visible.length} players`;$("#rosterList").innerHTML=visible.length?visible.map(p=>`<button class="player ${p.id===state.selected?"selected":""}" data-id="${p.id}" role="option" aria-selected="${p.id===state.selected}" style="--role:${roleColor(p.role)}"><span class="avatar">${p.name.slice(0,2)}</span><span class="player-copy"><strong>${p.name}</strong><small>${p.team}</small></span><span class="player-meta"><b>${p.role}</b><span>${p.strength}</span></span></button>`).join(""):`<p class="empty">No matching players.</p>`;$$('.player').forEach((el,i)=>{el.onclick=()=>{state.selected=+el.dataset.id;setMode("reading")};el.onmouseenter=()=>{state.hovered=+el.dataset.id;renderPeek()};el.onpointerdown=e=>{if(e.button===2)openRosterRadial(e,+el.dataset.id)};el.oncontextmenu=e=>e.preventDefault();el.onkeydown=e=>{if(["ArrowDown","ArrowUp","Home","End"].includes(e.key)){e.preventDefault();const list=$$('.player');const n=e.key==="Home"?0:e.key==="End"?list.length-1:Math.max(0,Math.min(list.length-1,i+(e.key==="ArrowDown"?1:-1)));list[n]?.focus();}}});renderPeek()}
function renderPeek(){const p=players.find(x=>x.id===state.hovered)||selectedPlayer();$("#peekCard").innerHTML=`<span class="eyebrow">PEEK</span><strong>${p.name}</strong><small>${p.role} · strength ${p.strength} · pool ${p.pool}</small>`}
function renderIdentity(){const p=selectedPlayer();$("#identity").style.setProperty("--role",roleColor(p.role));$("#identity").innerHTML=`<span class="identity-avatar">${p.name.slice(0,2)}</span><div><span class="eyebrow">ATHLETE IDENTITY</span><h2>${p.name}</h2><div class="identity-line"><b class="role-glyph">${p.role}</b><span>·</span><span>${p.team}</span></div></div><div class="identity-metrics"><span>CORE AVERAGE<b>${p.strength}</b></span><span>POOL DEPTH<b>${p.pool}</b></span><span>90+ CHAMPIONS<b>${champions.filter(c=>c.mastery>=90).length}</b></span></div>`}
function statValues(){return baseByPlayer[state.selected]||baseByPlayer[13]}
function renderStats(){const c=selectedChampion(),base=statValues();let gains=0,waste=0;const stats=coreNames.map((name,i)=>{const raw=base[i]*(1+c.buff),effective=Math.min(100,raw),gain=effective-base[i];gains+=gain;waste+=Math.max(0,raw-100);return `<div class="stat"><label><span>${name}</span><b>${base[i]} → ${effective.toFixed(0)}</b></label><div class="stat-track"><i class="base" style="width:${base[i]}%"></i><i class="effective" style="width:${effective}%"></i>${raw>100?`<i class="waste" style="width:${Math.min(18,raw-100)}%"></i>`:""}</div></div>`}).join("");const real=gains/8;$("#stats").innerHTML=`<div class="stats-head"><div><span class="eyebrow">CORE MECHANICS · BASE → EFFECTIVE → REALIZED</span><h3>${c.name} · +${Math.round(c.buff*100)}% nominal</h3></div><div class="buff-story"><span>${waste>0?`${waste.toFixed(0)} points capped · wasted buff`:"No capped stats"}</span><strong>+${real.toFixed(1)} real gain</strong></div></div><div class="stat-layout"><div class="core-grid">${stats}</div><div class="tendencies"><span>Shotcalling</span><b>56</b><span>Roaming</span><b>13</b><span>Aggressive</span><b>40</b><span>Ego</span><b>57</b></div></div>`}
function bandFor(m){return m>=90?90:m>=80?80:m>=70?70:0}function bandMeta(b){return b===90?["90+ · signature · max buff","var(--amber4)","color-mix(in srgb,var(--surface2) 88%,var(--amber4))"]:b===80?["80+ · expert","var(--amber3)","color-mix(in srgb,var(--surface2) 92%,var(--amber3))"]:b===70?["70+ · practiced","var(--amber2)","color-mix(in srgb,var(--surface2) 95%,var(--amber2))"]:["BELOW 70 · developing","var(--amber1)","var(--surface)"]}
function renderPool(){const query=state.poolQuery.toLowerCase(),list=champions.filter(c=>c.name.toLowerCase().includes(query));$("#poolSummary").textContent=`${list.length} records`;$("#poolBands").innerHTML=[90,80,70,0].map(b=>{const items=list.filter(c=>bandFor(c.mastery)===b),[label,color,bg]=bandMeta(b),collapsed=state.floor>b&&b!==0;return `<section class="band ${collapsed?"collapsed":""}" style="--band-color:${color};--band-bg:${bg}"><header class="band-head"><strong>${label}</strong><span>${items.length}</span>${collapsed?`<span>collapsed rail</span>`:""}</header><div class="champions">${items.map(c=>`<button class="champion ${c.id===state.champion?"selected":""}" data-champion="${c.id}" style="--mastery:${color}">${c.recent?'<i class="recent"></i>':''}<span class="portrait"><img src="${c.portrait}" alt="" style="${portraitStyle(c.id)}"></span><span class="champion-copy"><strong>${c.name}</strong><small>${Math.round(c.buff*100)}% nominal buff</small></span><b class="mastery">${c.mastery}</b></button>`).join("")}</div></section>`}).join("");$$('.champion').forEach(el=>{el.onclick=()=>{state.champion=el.dataset.champion;setMode("digging")};el.onpointerdown=e=>{if(e.button===2)openChampionRadial(e,el.dataset.champion)};el.oncontextmenu=e=>e.preventDefault()})}
function renderPins(){const tray=$("#pinTray");tray.classList.toggle("visible",state.pins.length>0||state.pinnedChampion);$("#pins").innerHTML=state.pins.map(id=>{const p=players.find(x=>x.id===id);return `<button class="pin" data-unpin="${id}">${p.name} ×</button>`}).join("")+(state.pinnedChampion?`<button class="pin" id="unpinChampion">${champions.find(c=>c.id===state.pinnedChampion).name} ×</button>`:"");$$('[data-unpin]').forEach(b=>b.onclick=()=>{state.pins=state.pins.filter(id=>id!==+b.dataset.unpin);renderPins();if(state.pins.length<2&&state.mode==="comparing")setMode("reading")});if($("#unpinChampion"))$("#unpinChampion").onclick=()=>{state.pinnedChampion=null;renderPins()}}
function pin(id){if(!state.pins.includes(id))state.pins.push(id);renderPins();if(state.pins.length>=2)setMode("comparing")}
function renderCompare(){const ids=[...state.pins];while(ids.length<3)ids.push(players.find(p=>!ids.includes(p.id)).id);$("#compare").innerHTML=`<span class="eyebrow">COMPARE · SHARED AXES</span><div class="compare-grid">${ids.slice(0,3).map(id=>{const p=players.find(x=>x.id===id),vals=baseByPlayer[id]||baseByPlayer[13];return `<button class="compare-col" data-read="${id}"><h3>${p.name} · ${p.role}</h3>${coreNames.map((n,i)=>`<div class="compare-stat"><span>${n}</span><b>${vals[i]}</b></div>`).join("")}<div class="shared">Shared champions · Swordman · Dark Mage</div></button>`}).join("")}</div>`;$$('[data-read]').forEach(b=>b.onclick=()=>{state.selected=+b.dataset.read;setMode("reading")})}
function renderScan(){const c=selectedChampion();const ranked=[...players].sort((a,b)=>(b.strength*(1+c.buff))-(a.strength*(1+c.buff)));$("#scan").innerHTML=`<span class="eyebrow">ROSTER SCAN</span><h2>Realized gain on ${c.name}</h2><div class="scan-controls"><select><option>Realized gain on ${c.name}</option><option>Mastery of ${c.name}</option><option>Core mechanics average</option><option>Role: ${selectedPlayer().role}</option></select></div>${ranked.map((p,i)=>`<button class="rank-row" data-read="${p.id}"><b>${i+1}</b><strong>${p.name}</strong><span>${p.role} · ${p.team}</span><b>+${Math.min(20,p.strength*c.buff).toFixed(1)}</b></button>`).join("")}`;$$('[data-read]').forEach(b=>b.onclick=()=>{state.selected=+b.dataset.read;setMode("reading")})}
function render(){renderRoster();renderIdentity();renderStats();renderPool();renderPins();renderCompare();renderScan()}
function showRadial(e,items){e.preventDefault();const r=$("#radial");state.radial={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,items};r.hidden=false;r.style.left=`${e.clientX}px`;r.style.top=`${e.clientY}px`;r.innerHTML=items.map((it,i)=>it?`<button class="${["north","east","south","west"][i]}" data-action="${i}">${it.label}</button>`:"").join("")+`<div class="radial-dead">release<br>to cancel</div>`;$$('[data-action]').forEach(b=>b.onclick=()=>{items[+b.dataset.action].run();closeRadial()})}
function openRosterRadial(e,id){showRadial(e,[{label:"Pin to compare",run:()=>pin(id)},{label:"Open",run:()=>{state.selected=id;setMode("reading")}},{label:"Rank by role",run:()=>{state.selected=id;setMode("scanning")}},{label:"Copy",run:()=>navigator.clipboard?.writeText(players.find(p=>p.id===id).name)}])}
function openChampionRadial(e,id){state.champion=id;showRadial(e,[{label:"Who plays best?",run:()=>setMode("scanning")},{label:"Pin champion",run:()=>{state.pinnedChampion=id;renderPins()}},{label:"Compare champion",run:()=>{if(state.pins.length<2)pin(state.selected);setMode("comparing")}},null])}
function closeRadial(){$("#radial").hidden=true;state.radial=null}
document.addEventListener("pointermove",e=>{if(!state.radial)return;const dx=e.clientX-state.radial.startX,dy=e.clientY-state.radial.startY,d=Math.hypot(dx,dy),idx=d<44?-1:Math.abs(dx)>Math.abs(dy)?(dx>0?1:3):(dy>0?2:0);$$('[data-action]').forEach(b=>b.classList.toggle('armed',+b.dataset.action===idx))});
document.addEventListener("pointerup",e=>{if(!state.radial)return;const dx=e.clientX-state.radial.startX,dy=e.clientY-state.radial.startY,d=Math.hypot(dx,dy);if(d<44){closeRadial();return}const idx=Math.abs(dx)>Math.abs(dy)?(dx>0?1:3):(dy>0?2:0);state.radial.items[idx]?.run();closeRadial()});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(!$("#radial").hidden)closeRadial();else setMode("reading")}if(e.key==="/"&&!["INPUT","SELECT"].includes(document.activeElement.tagName)){e.preventDefault();setMode("hunting");$("#rosterSearch").focus()}});
$("#rosterSearch").oninput=e=>{state.query=e.target.value;renderRoster()};$("#poolSearch").oninput=e=>{state.poolQuery=e.target.value;renderPool()};$("#teamFilter").onchange=e=>{state.team=e.target.value;renderRoster()};$("#contractToggle").onclick=e=>{state.contract=state.contract==="all"?"free":state.contract==="free"?"contracted":"all";e.currentTarget.textContent=state.contract==="all"?"All contracts":state.contract;renderRoster()};
$$('[data-role]').forEach(b=>b.onclick=()=>{$$('[data-role]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.role=b.dataset.role;renderRoster()});$$('[data-floor]').forEach(b=>b.onclick=()=>{$$('[data-floor]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.floor=+b.dataset.floor;renderPool()});
$("#lockLayout").onchange=e=>{state.lock=e.target.checked;$("#prototype").classList.toggle("layout-locked",state.lock)};$("#reduceMotion").onchange=e=>$("#prototype").classList.toggle("reduce-motion",e.target.checked);$("#themeButton").onclick=()=>{const root=document.documentElement;root.dataset.theme=root.dataset.theme==="light"?"dark":"light"};$("#lightThumb").onclick=()=>{document.documentElement.dataset.theme="light";setMode("reading",true)};$("#filterToggle").onclick=()=>$("#filters").toggleAttribute("hidden");
render();
